/* eslint-disable */
/**
 * Generated API stub for local builds. Regenerated by `npx convex dev`.
 */
import { anyApi, componentsGeneric } from "convex/server";

export const api = anyApi;
export const internal = anyApi;
export const components = componentsGeneric();
