/* eslint-disable */
/**
 * Generated server stub. Regenerated by `npx convex dev`.
 */
export {
  action,
  httpAction,
  internalAction,
  internalMutation,
  internalQuery,
  mutation,
  query,
} from "convex/server";

export const api = undefined;
export const components = undefined;
